music-hub/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'homes#tops'
  get '/about' => 'homes#about'
  get 'events', to: 'events#events', as: 'user_calendar'
  get 'events_artist', to: 'events#event', as: 'artist_calendar'

  #artistお気に入り登録・解除
  post '/artists/:artist_id/favorites' => "favorites#create"
  delete '/artists/:artist_id/favorites' => "favorites#destroy"
  get '/users/:id/favorites' => "users#favorite",as: 'favorites'

  #recommendお気に入り登録・解除
  post '/artists/:artist_id/recommends/:recommend_id/myrecommends' => "myrecommends#create"
  delete '/artists/:artist_id/recommends/:recommend_id/myrecommends' => "myrecommends#destroy"
  get '/users/:id/myrecommends' => "users#myrecommend",as: 'myrecommends'

  #userのfullcalendaer表示用
  get '/users/:user_id/events' => "events#user_index",as: 'user_events'

  #userのフォロー、フォロワーのviewページ
  get 'users/:id/follows' => 'users#following',as: 'follows'
  get 'users/:id/followers' => 'users#followers',as: 'followers'

  resources :users, only: [:show, :edit, :update, :destroy]

  resources :artists, only: [:index, :new, :edit, :create, :update, :destroy] do
    get :search, on: :collection
    #eventsのindexをartistのfullcalendar表示用として使用
    resources :events, only: [:index, :destroy, :update]
    resources :recommends,only: [:index, :show, :create, :destroy] do
      resources :comments,only: [:create, :destroy]
    end
  end

  resources :events, only: [:create]
  resources :relationships, only: [:create, :destroy]
end

music-hub/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, uniqueness: { case_sensitive: :false }, length: { maximum: 20 }, presence: true
  validates :introduction,length:{maximum:150}
  validates :email, presence: true

  attachment :image

  has_many :artists
  has_many :events, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :recommends, dependent: :destroy
  has_many :myrecommends, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  # ユーザーをフォローする
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  # ユーザーをアンフォローする
  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    self.followings.include?(other_user)
  end
end

music-hub/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  def show
  	@event = Event.new
    @favorites = Favorite.where(user_id: params[:id])
    @user = User.find(params[:id])
    @myrecommends = Myrecommend.where(user_id: params[:id])
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
       redirect_to user_path(current_user)
    else
       flash[:user_error] = "全て入力してください。また、ユーザー名20文字以内・自己紹介150文字以内で入力をお願いします。"
       redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @user = User.find(current_user.id)
    @user.destroy
    redirect_to root_path
  end

  def favorite
    @favorites = Favorite.where(user_id: params[:id])
  end

  def myrecommend
    @myrecommends = Myrecommend.where(user_id: params[:id])
  end

  def following
    @user  = User.find(params[:id])
    @users = @user.followings
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
  end

  private
  def user_params
    params.require(:user).permit(:name, :image, :introduction, :email)
  end

  #URL直打ち防止
  def correct_user
    @user = User.find(params[:id])
    redirect_to root_path unless @user == current_user
  end
end

music-hub/app/helpers/users_helper.rb
module UsersHelper
end

music-hub/app/views/users/_follow.html.erb
<% if current_user.following?(user) %>
<%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }, remote: true) do |f| %>
<%= hidden_field_tag :follow_id, user.id %>
<%= f.submit 'フォロー中', class: "btn btn-primary col-xs-12" %>
<% end %>
<% else %>
<%= form_for(current_user.relationships.build, remote: true) do |f| %>
<%= hidden_field_tag :follow_id, user.id %>
<%= f.submit 'フォローする', class: "btn btn-default col-xs-12" %>
<% end %>
<% end %>

music-hub/app/views/users/_myrecommend.html.erb
<% if Myrecommend.find_by(user_id: current_user.id, artist_id: artist.id, recommend_id: recommend.id ) %>
<%= link_to "/artists/#{artist.id}/recommends/#{recommend.id}/myrecommends", method: :delete, remote: true do %>
<i class="glyphicon glyphicon-star myrecommend-heart" aria-hidden="true"></i>
<% end %>
<% else %>
<%= link_to "/artists/#{artist.id}/recommends/#{recommend.id}/myrecommends", method: :post,remote: true do %>
<i class="glyphicon glyphicon-star-empty myrecommend-heart" aria-hidden="true"></i>
<% end %>
<% end %>

music-hub/app/views/users/edit.html.erb
<div class="container">
    <div class="row">
        <h3 class="text-center"><strong>登録情報編集</strong></h3>
    </div>
    <div class="row">
        <p align="center"><%= flash[:user_error] %></p>
        <div class="col-xs-12">
            <div class="col-xs-10 col-xs-offset-1">
                <%= form_for(@user) do |f| %>
                <div class="form-group">
                    <table class="table user-table">
                        <tr>
                            <th class="col-xs-3">ユーザー名</th>
                            <td>
                                <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "form-control" %>
                            </td>
                        </tr>
                        <tr>
                            <th class="col-xs-3">プロフィール画像</th>
                            <td>
                                <div class="col-xs-4">
                                    <%= attachment_image_tag @user, :image, size:"100x100",fallback: "no_image.jpg", id: "file-preview" %>
                                </div>
                                <div class="col-xs-8">
                                    <%= f.attachment_field :image, class: "btn btn-default user_attachment_field", id: "image_select"%>
                                    <label for="image_select" class="btn btn-default user_attachment_field" style="display: block;">画像選択</label>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <th class="col-xs-3">自己紹介</th>
                            <td>
                                <%= f.text_area :introduction, autofocus: true, autocomplete: "introduction", class: "form-control" %>
                            </td>
                        </tr>
                        <tr>
                            <th class="col-xs-3">メールアドレス</th>
                            <td>
                                <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
                            </td>
                        </tr>
                        <tr>
                            <td align="center" colspan="12">
                                <%= f.submit "編集内容を保存する" ,class: "btn btn-lg btn-primary" %>
                                <%= link_to '退会する',user_path(@user.id),method: :delete, data: { confirm: '退会してよろしいですか？' }, class: "btn btn-lg btn-danger" %>
                            </td>
                        </tr>
                    </table>
                </div>
                <% end %>
            </div>
        </div>
    </div>
</div>
<!-- 画像選択した際に、選択した画像を表示させるjavascript -->
<script>
document.getElementById("image_select").addEventListener("change", function(e) {
    // 1枚だけ表示する
    var file = e.target.files[0];

    // ファイルのブラウザ上でのURLを取得する
    var blobUrl = window.URL.createObjectURL(file);

    // img要素に表示
    var img = document.getElementById("file-preview");
    img.src = blobUrl;
});
</script>

music-hub/app/views/users/favorite.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1" align="center">
            <h3><strong>アーティストお気に入り一覧</strong></h3>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <% if @favorites.empty?  %>
            <div class="searched">
                <h1>お気に入りのアーティストはまだいません。</h1>
            </div>
            <% end %>
            <% @favorites.each do |favorite| %>
            <table class="table">
                <tr>
                    <th class="col-xs-2">
                        <%= attachment_image_tag favorite.artist,:image,size:"100x100",fallback: "no_image.jpg" %><br>
                    </th>
                    <td class="col-xs-6">
                        <h4 class="favorite-artist">
                            <%= favorite.artist.name %>
                        </h4>
                        <%= favorite.artist.explanation %>
                    </td>
                    <td class="col-xs-4" align="right">
                        <p class="favorite-artist-link">
                            <%= link_to "スケジュールを確認する", artist_events_path(favorite.artist_id) %>
                        </p>
                    </td>
                </tr>
            </table>
            <% end %>
        </div>
    </div>
</div>

music-hub/app/views/users/followers.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1" align="center">
            <h3><strong>フォロワー</strong></h3>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <% if @users.empty?  %>
            <div class="searched">
                <h1>フォロワーはまだいません。</h1>
            </div>
            <% end %>
            <% @users.each do |user| %>
            <table class="table devise-table">
                <tr>
                    <th class="col-xs-1">
                        <%= attachment_image_tag user, :image, size:"100x100", fallback: "no_image.jpg"%><br>
                    </th>
                    <td class="col-xs-8">
                        <h4>
                            <%= link_to "#{user.name}", user_path(user.id) %>
                        </h4>
                        <p>
                            <%= user.introduction %>
                        </p>
                    </td>
                    <td class="col-xs-1" align="right" id="follow-<%= @user.id %>">
                        <% unless current_user.id == user.id %>
                        <%= render partial: "follow", locals: { user: user} %>
                        <% end %>
                    </td>
                </tr>
            </table>
            <% end %>
        </div>
    </div>
</div>

music-hub/app/views/users/following.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1" align="center">
            <h3><strong>フォロー中</strong></h3>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <% if @users.empty?  %>
            <div class="searched">
                <h1>フォローしているユーザーはまだいません。</h1>
            </div>
            <% end %>
            <% @users.each do |user| %>
            <table class="table devise-table">
                <tr>
                    <th class="col-xs-1">
                        <%= attachment_image_tag user, :image, size:"100x100", fallback: "no_image.jpg"%><br>
                    </th>
                    <td class="col-xs-8">
                        <h4>
                            <%= link_to "#{user.name}", user_path(user.id) %>
                        </h4>
                        <p>
                            <%= user.introduction %>
                        </p>
                    </td>
                    <td class="col-xs-1" align="right" id="follow-<%= @user.id %>">
                        <% unless current_user.id == user.id %>
                        <%= render partial: "follow", locals: { user: user} %>
                        <% end %>
                    </td>
                </tr>
            </table>
            <% end %>
        </div>
    </div>
</div>

music-hub/app/views/users/myrecommend.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1" align="center">
            <h3><strong>お気に入りミュージック一覧</strong></h3>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <% if @myrecommends.empty?  %>
            <div class="searched">
                <h1>お気に入りのミュージックはまだありません。</h1>
            </div>
            <% end %>
            <% @myrecommends.each do |myrecommend| %>
            <table class="table myrecommend-table">
                <tr>
                    <th class="col-xs-6">
                        <p class="glyphicon glyphicon-user myrecommend-artist-name">
                            <%= myrecommend.recommend.artistname %>
                        </p><br>
                        <p class="glyphicon glyphicon-headphones myrecommend-song">
                            <%= myrecommend.recommend.song %>
                        </p>
                    </th>
                    <td class="col-xs-2" id="myrecommends-<%= (myrecommend.recommend.id) %>">
                        <%= render partial: "myrecommend", locals: { recommend: myrecommend.recommend, artist: myrecommend.artist} %>
                    </td>
                    <td class="col-xs-4" align="center">
                        <p class="to-comment">
                            <%= link_to "コメントページへ",artist_recommend_path(myrecommend.artist_id,myrecommend.recommend_id) %>
                        </p>
                    </td>
                </tr>
            </table>
            <% end %>
        </div>
    </div>
</div>

music-hub/app/views/users/show.html.erb
<div class="mypage-top"></div>
<div class="container">
    <div class="row">
        <div class="col-xs-6">
            <div class="col-xs-3">
                <%= attachment_image_tag @user, :image, size:"120x120",fallback: "no_image.jpg", id: "file-preview" %>
            </div>
            <div class="col-xs-5">
                <h3>
                    <%= @user.name%>
                </h3>
                <h4>
                    <%= link_to "#{@user.followings.count}", follows_path(@user) %> フォロー中</h4>
                <h4>
                    <%= link_to "#{@user.followers.count}", followers_path(@user) %> フォロワー</h4>
            </div>
            <div class="col-xs-4 profile-edit" id="follow-<%= @user.id %>">
                <% if @user.id == current_user.id %>
                <%= link_to "プロフィールを編集", edit_user_path(@user),class: "btn btn-default col-xs-12"%>
                <%= link_to "マイカレンダー", user_events_path(current_user),class: "btn btn-info btn-lg col-xs-12 profile-button" %>
                <% else %>
                <%= render partial: "follow", locals: { user: @user} %>
                <% end %>
            </div>
            <div class="col-xs-12 profile-introduction">
                <p>
                    <%= @user.introduction %>
                </p>
            </div>
            <%= link_to "お気に入りアーティスト一覧", favorites_path(@user), class: "btn btn-primary btn-lg col-xs-6 col-xs-offset-3 profile-button" %>
            <%= link_to "お気に入りミュージック一覧", myrecommends_path(@user), class: "btn btn-primary btn-lg col-xs-6 col-xs-offset-3 profile-button" %>
            <% if @user.id == current_user.id %>
            <%= link_to "アーティスト新規作成", new_artist_path, class: "btn btn-primary btn-lg col-xs-6 col-xs-offset-3 profile-button" %>
            <% end %>
        </div>
        <div class="col-xs-6">
            <div class="col-xs-12 profile-border">
                <p class="col-xs-9 favorite-artist">お気に入りアーティスト</p>
                <p class="favorite-artist">
                    <%= link_to '>>もっと見る',favorites_path(@user) ,class: "link" %>
                </p><br>
                <% @favorites.first(2).each do |favorite|%>
                <%= link_to artist_events_path(favorite.artist_id) do%>
                <div class="col-xs-6">
                    <%= attachment_image_tag favorite.artist, :image, size:"120x120", format: 'jpeg' , fallback: "no_image.jpg"%>
                    <p>
                        <%= favorite.artist.name%>
                    </p>
                </div>
                <% end %>
                <% end %>
            </div>
            <div class="col-xs-12">
                <p class="col-xs-9 favorite-music">お気に入りミュージック</p>
                <p class="favorite-music">
                    <%= link_to '>>もっと見る',myrecommends_path(@user) ,class: "link" %>
                </p>
                <% @myrecommends.first(6).each do |myrecommend|%>
                <%= link_to artist_recommend_path(myrecommend.artist_id,myrecommend.recommend_id) do%>
                <div class="col-xs-6">
                    <h4><i class="glyphicon glyphicon-user mypage-myreco-artistname">
                            <%= myrecommend.recommend.artistname %></i><br>
                        <i class="glyphicon glyphicon-headphones">
                            <%= myrecommend.recommend.song %></i></h4>
                </div>
                <% end %>
                <% end %>
            </div>
        </div>
    </div>
    <div class="mypage-footer"></div>
</div>