music-hub/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'homes#tops'
  get '/about' => 'homes#about'
  get 'events', to: 'events#events', as: 'user_calendar'
  get 'events_artist', to: 'events#event', as: 'artist_calendar'

  #artistお気に入り登録・解除
  post '/artists/:artist_id/favorites' => "favorites#create"
  delete '/artists/:artist_id/favorites' => "favorites#destroy"
  get '/users/:id/favorites' => "users#favorite",as: 'favorites'

  #recommendお気に入り登録・解除
  post '/artists/:artist_id/recommends/:recommend_id/myrecommends' => "myrecommends#create"
  delete '/artists/:artist_id/recommends/:recommend_id/myrecommends' => "myrecommends#destroy"
  get '/users/:id/myrecommends' => "users#myrecommend",as: 'myrecommends'

  #userのfullcalendaer表示用
  get '/users/:user_id/events' => "events#user_index",as: 'user_events'

  #userのフォロー、フォロワーのviewページ
  get 'users/:id/follows' => 'users#following',as: 'follows'
  get 'users/:id/followers' => 'users#followers',as: 'followers'

  resources :users, only: [:show, :edit, :update, :destroy]

  resources :artists, only: [:index, :new, :edit, :create, :update, :destroy] do
    get :search, on: :collection
    #eventsのindexをartistのfullcalendar表示用として使用
    resources :events, only: [:index, :destroy, :update]
    resources :recommends,only: [:index, :show, :create, :destroy] do
      resources :comments,only: [:create, :destroy]
    end
  end

  resources :events, only: [:create]
  resources :relationships, only: [:create, :destroy]
end

music-hub/app/models/event.rb
class Event < ApplicationRecord

	belongs_to :user
	belongs_to :artist

	validates :title, {presence: true,length: {maximum: 20}}
	validates :start, presence: true
	validates :end, presence: true
	validates :share, presence: true
	validates :venue, {presence: true,length: {maximum: 30}}
	validates :url, {presence: true,format: /\A#{URI::regexp(%w(http https))}\z/}
	validates :memo, {presence: true, length: {maximum: 150}}

	#スケジュールをシェアするかしないか
	enum share: { シェアする:0, シェアしない:1 }
end

music-hub/app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :correct_user, only: [:user_index]
	before_action :authenticate_user!

	#アーティストページ
	def index
		@events = Event.where(artist_id: params[:artist_id])
		@artist = Artist.find(params[:artist_id])
		@event = Event.new
	end

	def create
		@event = Event.new(event_params)
		@event.user_id = current_user.id
		@event_artist = Artist.find(params[:artist_event][:id])
		@event.artist_id = @event_artist.id
	  	if @event.save
		   redirect_back(fallback_location: root_path)
	    else
	       flash[:event_error] = "全て入力してください。また、タイトル20文字以内・会場30文字以内、メモ150文字以内で入力をお願いします。"
           redirect_back(fallback_location: root_path)
	    end
	end

	def destroy
		@event = Event.find(params[:id])
	    @event.destroy
	    redirect_back(fallback_location: root_path)
	end

	def update
		@event = Event.find(params[:id])
		@event.user_id = current_user.id
        if @event.update(event_params)
           redirect_back(fallback_location: root_path)
       	else
       	   flash[:event_error] = "全て入力してください。また、タイトル20文字以内・会場30文字以内、メモ150文字以内で入力をお願いします。"
           redirect_back(fallback_location: root_path)
       	end
	end

	#ユーザーページ
  	def user_index
  		@event = Event.new
  		@user = current_user
  		@favorites = Favorite.where(user_id: current_user.id)
		@events = Event.where(user_id: current_user.id)
 	end

    #ユーザーページのカレンダー表示
    def events
    	@events = Event.where(user_id: current_user.id)
    	# render :json => @event
	    respond_to do |format|
	      format.json {
	        render json:
	        @events.to_json(
	          only: [:id, :user_id, :title, :artist_id, :venue, :start, :end, :memo, :share]
	        )
	      }
	   	end
    end

    #アーティストページのカレンダー表示
    def event
    	@event = Event.where(artist_id: params[:artist_id],share: 0)
	    respond_to do |format|
	      format.json {
	        render json:
	        @event.to_json(
	          only: [:id, :title, :start, :end]
	        )
	      }
	   	end
    end

	private
	def favorite_params
    	params.require(:artist_event).permit(:id)
  	end
	def event_params
		params.require(:event).permit(:artist_id, :title, :venue, :start, :end,:share, :url, :memo )
	end
	#URL直打ち防止
	def correct_user
	    @user = User.find(params[:user_id])
	    redirect_to root_path unless @user == current_user
	end
end

music-hub/app/helpers/events_helper.rb
module EventsHelper
end

music-hub/app/views/events/_artist_edit.html.erb
<% events.each do |event| %>
<div id='inputScheduleEditForm<%= event.id %>' class="modal fade" tabindex="-1">
    <div class="modal-dialog modal-nm">
        <div class="modal-content">
            <div class="row artist-event-edit">
                <h3 class="modal-title" align="center"><strong>スケジュール</strong></h3>
            </div>
            <%= form_for(@event) do |f| %>
            <table class="col-xs-10 col-xs-offset-1 artist-event-edit">
                <tr>
                    <th class="col-xs-5">
                        登録ユーザー：</th>
                    <td>
                        <%= link_to user_path(event.user_id) do%>
                        <%= event.user.name%>
                        <% end %>
                    </td>
                </tr>
                <tr>
                    <th class="col-xs-5">
                        アーティスト：</th>
                    <td>
                        <%= event.artist.name%>
                        <%= hidden_field :artist_event, :id, :value => event.artist_id %>
                    </td>
                </tr>
                <tr>
                    <th class="col-xs-5">タイトル：</th>
                    <td>
                        <%= event.title%>
                        <%= f.hidden_field :title, :value => event.title %>
                    </td>
                </tr>
                <tr>
                    <th class="col-xs-5">開始：</th>
                    <td>
                        <%= event.start.strftime("%Y年%m月%d日 %H時%M分")%>
                        <%= f.hidden_field :start, :value => event.start %>
                    </td>
                </tr>
                <tr>
                    <th class="col-xs-5">
                        終了：</th>
                    <td>
                        <%= event.end.strftime("%Y年%m月%d日 %H時%M分")%>
                        <%= f.hidden_field :end, :value => event.end %>
                        <%= f.hidden_field :share, :value => "シェアしない" %>
                    </td>
                </tr>
                <tr>
                    <th class="col-xs-5">会場：</th>
                    <td>
                        <%= event.venue%>
                        <%= f.hidden_field :venue, :value => event.venue %>
                    </td>
                </tr>
                <tr>
                    <th class="col-xs-5">URL：</th>
                    <td>
                        <%= raw Rinku.auto_link(event.url, :all, 'target="_blank"') %>
                        <%= f.hidden_field :url, :value => event.url %>
                    </td>
                </tr>
                <tr>
                    <th class="col-xs-5">メモ：</th>
                    <td>
                        <%= event.memo%>
                        <%= f.hidden_field :memo, :value => event.memo %>
                    </td>
                </tr>
            </table>
            <div class="modal-footer">
                <div align="center">
                    <% if event.user_id == current_user.id %>
                    <botton class="btn btn-default">登録済み</botton>
                    <% else %>
                    <%= f.submit "登 録 す る", class: "btn btn-primary"%>
                    <% end%>
                    <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
                </div>
            </div>
            <% end %>
        </div>
    </div>
</div>
<% end %>

music-hub/app/views/events/_artistedit.html.erb
<% events.each do |event| %>
<div id='inputScheduleEditForm<%= event.id %>' class="modal fade" tabindex="-1">
    <div class="modal-dialog modal-nm">
        <div class="modal-content">
            <div class="row artist-event-edit">
                <h3 class="modal-title" align="center"><strong>スケジュール</strong></h3>
            </div>
            <%= form_for(@event) do |f| %>
            <table class="col-xs-10 col-xs-offset-1 artist-event-edit">
                <tr>
                    <th class="col-xs-5">
                        登録ユーザー：</th>
                    <td>
                        <%= link_to user_path(event.user_id) do%>
                        <%= event.user.name%>
                        <% end %>
                    </td>
                </tr>
                <tr>
                    <th class="col-xs-5">
                        アーティスト：</th>
                    <td>
                        <%= event.artist.name%>
                        <%= hidden_field :artist_event, :id, :value => event.artist_id %>
                    </td>
                </tr>
                <tr>
                    <th class="col-xs-5">タイトル：</th>
                    <td>
                        <%= event.title%>
                        <%= f.hidden_field :title, :value => event.title %>
                    </td>
                </tr>
                <tr>
                    <th class="col-xs-5">開始：</th>
                    <td>
                        <%= event.start.strftime("%Y年%m月%d日 %H時%M分")%>
                        <%= f.hidden_field :start, :value => event.start %>
                    </td>
                </tr>
                <tr>
                    <th class="col-xs-5">
                        終了：</th>
                    <td>
                        <%= event.end.strftime("%Y年%m月%d日 %H時%M分")%>
                        <%= f.hidden_field :end, :value => event.end %>
                        <%= f.hidden_field :share, :value => "シェアしない" %>
                    </td>
                </tr>
                <tr>
                    <th class="col-xs-5">会場：</th>
                    <td>
                        <%= event.venue%>
                        <%= f.hidden_field :venue, :value => event.venue %>
                    </td>
                </tr>
                <tr>
                    <th class="col-xs-5">URL：</th>
                    <td>
                        <%= raw Rinku.auto_link(event.url, :all, 'target="_blank"') %>
                        <%= f.hidden_field :url, :value => event.url %>
                    </td>
                </tr>
                <tr>
                    <th class="col-xs-5">メモ：</th>
                    <td>
                        <%= event.memo%>
                        <%= f.hidden_field :memo, :value => event.memo %>
                    </td>
                </tr>
            </table>
            <div class="modal-footer">
                <div align="center">
                    <%= f.submit "登 録 す る", class: "btn btn-primary"%>
                    <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
                </div>
            </div>
            <% end %>
        </div>
    </div>
</div>
<% end %>

music-hub/app/views/events/_edit.html.erb
<% events.each do |event| %>
<div id='inputScheduleEditForm<%= event.id %>' class="modal fade" tabindex="-1">
    <div class="modal-dialog modal-nm">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" align="center"><strong>スケジュール編集</strong></h3>
            </div>
            <div class="col-xs-10 col-xs-offset-1 artist-event-edit">
                <%= form_with(model: event, url: artist_event_path(event.artist_id, event.id), method: :put) do |f| %>
                <div class="col-xs-5 artist-event-item">アーティスト：</div>
                <div class="col-xs-7 artist-event-item">
                    <strong>
                        <%= event.artist.name%></strong>
                </div>
                <div class="col-xs-5 artist-event-item">タイトル：</div>
                <div class="col-xs-7 artist-event-item">
                    <%= f.text_field :title ,class: 'form-control'%>
                </div>
                <div class="col-xs-5 ">開始：</div>
                <div class="col-xs-7 artist-event-item">
                    <%= f.datetime_field :start ,class: 'form-control'%>
                </div>
                <div class="col-xs-5 artist-event-item">終了：</div>
                <div class="col-xs-7 artist-event-item">
                    <%= f.datetime_field :end ,class: 'form-control'%>
                </div>
                <div class="col-xs-5 artist-event-item">
                    シェア：</div>
                <div class="col-xs-7 artist-event-item">
                    <%= f.select :share, [["シェアする", "シェアする"], ["シェアしない", "シェアしない"]], {}, {class: 'form-control'} %>
                </div>
                <div class="col-xs-5 artist-event-item">会場：</div>
                <div class="col-xs-7 artist-event-item">
                    <%= f.text_field :venue ,class: 'form-control'%>
                </div>
                <div class="col-xs-5 artist-event-item">URL：</div>
                <div class="col-xs-7 artist-event-item">
                    <%= f.url_field :url ,class: 'form-control'%>
                </div>
                <div class="col-xs-5 artist-event-item">メモ：</div>
                <div class="col-xs-7 artist-event-item">
                    <%= f.text_area :memo ,class: 'form-control'%>
                </div>
            </div>
            <div class="modal-footer">
                <div align="center">
                    <%= f.hidden_field :user_id, :value => current_user.id %>
                    <%= f.submit "編集する", class: "btn btn-primary" %>
                    <%= link_to "削除する", artist_event_path(event.artist_id, event.id), method: :delete, class: "btn btn-danger"%>
                    <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
                </div>
            </div>
            <% end %>
        </div>
    </div>
</div>
<% end %>

music-hub/app/views/events/_favorite.html.erb
<% if Favorite.find_by(user_id: current_user.id, artist_id: artist.id) %>
	<%= link_to "/artists/#{artist.id}/favorites", method: :delete, remote: true do %>
		<button type="button" class="btn btn-default col-xs-12">お気に入り解除</button>
	<% end %>
<% else %>
	<%= link_to "/artists/#{artist.id}/favorites", method: :post, remote: true do %>
		<button type="button" class="btn btn-primary col-xs-12">お気に入り登録</button>
	<% end %>
<% end %>

music-hub/app/views/events/index.html.erb
<div class="event-page">
    <div class="container">
        <div class="row">
            <div class="col-xs-3 artist-info">
                <div class="col-xs-12 event-artist-image">
                    <table>
                        <tr>
                            <th>
                                <%= attachment_image_tag @artist, :image, size:"80x80", fallback: "no_image.jpg" %>
                            </th>
                            <td>
                                <p class="event-artist-name">
                                    <%= @artist.name %>
                                </p>
                            </td>
                        </tr>
                    </table>
                </div>
                <div class="col-xs-12 artist-explanation">
                    <%= @artist.explanation %>
                </div>
                <div class="col-xs-12 artist-btn" id="favorite-<%= @artist.id %>">
                    <%= render partial: "favorite", locals: { artist: @artist } %>
                </div>
                <div class="col-xs-12 artist-btn">
                    <%= link_to 'みんなのおすすめへ', artist_recommends_path(@artist.id), class:"btn btn-info btn-lg col-xs-12"%>
                </div>
                <div class="col-xs-12 artist-btn">
                    <% if @artist.user_id == current_user.id%>
                    <%= link_to ' 編　　集 ', edit_artist_path(@artist.id), class:"btn btn-success col-xs-12"%>
                    <% end %>
                </div>
            </div>
            <div class="col-xs-9">
                <div id="calendar"></div>
                <div id="inputEditForm">
                    <%= render 'events/artist_edit', events: @events %>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
$(function() {
    function clearCalendar() {
        $('#calendar').html('');
    }
    $(document).on('turbolinks:before-cache', clearCalendar);

    $(document).on('turbolinks:load', function() {
        if ($('#calendar').length) {
            $('#calendar').fullCalendar({
                //events.jsonを参照させる（getの際にパラメータとして@user.idを持たせる）
                events: '/events_artist.json?artist_id=<%=@artist.id%>',
                //カレンダー上部を年月で表示させる
                titleFormat: 'YYYY年 M月',
                //曜日を日本語表示
                dayNamesShort: ['日', '月', '火', '水', '木', '金', '土'],
                //ボタンのレイアウト
                header: {
                    left: 'today prev,next',
                    center: 'title',
                    right: 'month agendaDay listMonth'
                },
                //終了時刻がないイベントの表示間隔
                defaultTimedEventDuration: '03:00:00',
                buttonText: {
                    prev: '前',
                    next: '次',
                    prevYear: '前年',
                    nextYear: '翌年',
                    today: '今日',
                    month: '月',
                    week: '週',
                    day: '日',
                    list: 'リスト'
                },
                selectable: true, // 選択可
                selectHelper: true, // 選択時にプレースホルダーを描画
                ignoreTimezone: false, // 自動選択解除
                navLinks: true,
                businessHours: true,
                eventLimit: true,

                timeZone: 'Asia/Tokyo',
                //スケジュールの時間表示を２４時間に
                timeFormat: "HH:mm",
                //スケジュールの色を変える
                eventColor: '#4682B4',
                //スケジュールの文字色を変える
                eventTextColor: '#DCDCDC',

                eventClick: function(calEvent, jsEvent, view) {
                    $(`#inputScheduleEditForm${calEvent.id}`).modal('show');
                },

                eventRender: function(event, element) {
                    element.css("font-size", "0.8em");
                    element.css("padding", "5px");
                }

            });
        }
    });
});
</script>

music-hub/app/views/events/user_index.html.erb
<div class="event-page">
    <div class="container">
        <div class="row">
            <p align="center">
                <%= flash[:event_error] %>
            </p>
            <div class="col-xs-3">
                <h3 align="center"><strong>マイカレンダー</strong></h3>
                <%= form_for(@event) do |f| %>
                <div class="col-xs-12 event-user-new">アーティスト：
                    <%= collection_select :artist_event, :id, @favorites, :artist_id, :name,  {}, class: 'form-control'%>
                    <%= f.hidden_field :event_id, :value => nil %>
                </div>
                <div class="col-xs-12 event-user-new">タイトル：
                    <%= f.text_field :title ,class: 'form-control'%>
                </div>
                <div class="col-xs-12 event-user-new">開始：
                    <%= f.datetime_field :start ,class: 'form-control'%>
                </div>
                <div class="col-xs-12 event-user-new">終了：
                    <%= f.datetime_field :end ,class: 'form-control'%>
                </div>
                <div class="col-xs-12 event-user-new">シェア：
                    <%= f.select :share, [["シェアする", "シェアする"], ["シェアしない", "シェアしない"]], {include_blank: "選択して下さい"}, {class: 'form-control'} %>
                </div>
                <div class="col-xs-12 event-user-new">会場：
                    <%= f.text_field :venue ,class: 'form-control'%>
                </div>
                <div class="col-xs-12 event-user-new">URL：
                    <%= f.url_field :url ,class: 'form-control'%>
                </div><br>
                <div class="col-xs-12 event-user-new">メモ：
                    <%= f.text_area :memo ,class: 'form-control'%>
                </div>
                <div class="col-xs-12 event-new-btn">
                    <%= f.submit ' 追 加 す る ',class: 'btn btn-primary col-xs-12' %>
                </div>
                <% end %>
            </div>
            <div class="col-xs-9">
                <div id="calendar"></div>
                <div id="inputEditForm">
                    <%= render 'events/edit', events: @events %>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- カレンダーjavascript -->
<script>
$(function() {
    function clearCalendar() {
        $('#calendar').html('');
    }
    $(document).on('turbolinks:before-cache', clearCalendar);

    $(document).on('turbolinks:load', function() {
        if ($('#calendar').length) {
            $('#calendar').fullCalendar({
                //events.jsonを参照させる（getの際にパラメータとして@user.idを持たせる）
                events: '/events.json?user_id=<%=@user.id%>',
                //カレンダー上部を年月で表示させる
                titleFormat: 'YYYY年 M月',
                //曜日を日本語表示
                dayNamesShort: ['日', '月', '火', '水', '木', '金', '土'],
                //ボタンのレイアウト
                header: {
                    left: 'today prev,next',
                    center: 'title',
                    right: 'month agendaDay listMonth'
                },
                //終了時刻がないイベントの表示間隔
                defaultTimedEventDuration: '03:00:00',
                buttonText: {
                    prev: '前',
                    next: '次',
                    prevYear: '前年',
                    nextYear: '翌年',
                    today: '今日',
                    month: '月',
                    week: '週',
                    day: '日',
                    list: 'リスト'
                },
                selectable: true, // 選択可
                selectHelper: true, // 選択時にプレースホルダーを描画
                ignoreTimezone: false, // 自動選択解除
                navLinks: true,
                businessHours: true,
                eventLimit: true,

                timeZone: 'Asia/Tokyo',
                //スケジュールの時間表示を２４時間に
                timeFormat: "HH:mm",
                //スケジュールの色を変える
                eventColor: '#4682B4',
                //スケジュールの文字色を変える
                eventTextColor: '#DCDCDC',
                disableDragging: true,
                allDay: true,

                // event クリックで編集、削除
                eventClick: function(calEvent, jsEvent, view) {
                    jsEvent.preventDefault();
                    $(`#inputScheduleEditForm${calEvent.id}`).modal('show');
                },

                eventMouseover: function(event, jsEvent, view) {
                    jsEvent.preventDefault();
                }
            });
        }
    });
});
</script>