music-hub/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'homes#tops'
  get '/about' => 'homes#about'
  get 'events', to: 'events#events', as: 'user_calendar'
  get 'events_artist', to: 'events#event', as: 'artist_calendar'

  #artistお気に入り登録・解除
  post '/artists/:artist_id/favorites' => "favorites#create"
  delete '/artists/:artist_id/favorites' => "favorites#destroy"
  get '/users/:id/favorites' => "users#favorite",as: 'favorites'

  #recommendお気に入り登録・解除
  post '/artists/:artist_id/recommends/:recommend_id/myrecommends' => "myrecommends#create"
  delete '/artists/:artist_id/recommends/:recommend_id/myrecommends' => "myrecommends#destroy"
  get '/users/:id/myrecommends' => "users#myrecommend",as: 'myrecommends'

  #userのfullcalendaer表示用
  get '/users/:user_id/events' => "events#user_index",as: 'user_events'

  #userのフォロー、フォロワーのviewページ
  get 'users/:id/follows' => 'users#following',as: 'follows'
  get 'users/:id/followers' => 'users#followers',as: 'followers'

  resources :users, only: [:show, :edit, :update, :destroy]

  resources :artists, only: [:index, :new, :edit, :create, :update, :destroy] do
    get :search, on: :collection
    #eventsのindexをartistのfullcalendar表示用として使用
    resources :events, only: [:index, :destroy, :update]
    resources :recommends,only: [:index, :show, :create, :destroy] do
      resources :comments,only: [:create, :destroy]
    end
  end

  resources :events, only: [:create]
  resources :relationships, only: [:create, :destroy]
end

music-hub/app/models/recommend.rb
class Recommend < ApplicationRecord
	belongs_to :user
	belongs_to :artist
	has_many :myrecommends, dependent: :destroy
	has_many :comments, dependent: :destroy

	validates :artistname, {presence: true,length: {maximum: 20}}
	validates :song, {presence: true,length: {maximum: 20}}
	validates :url, presence: true
	validates :explanation, {presence: true,length: {maximum: 150}}
end

music-hub/app/controllers/recommends_controller.rb
class RecommendsController < ApplicationController
	before_action :authenticate_user!
	def index
		@artist = Artist.find(params[:artist_id])
		@recommends = Recommend.where(artist_id: @artist.id)
		@recommend = Recommend.new
	end

	def show
		@recommend = Recommend.find(params[:id])
		@artist = Artist.find(params[:artist_id])
		@comment = Comment.new
		@comments = Comment.where(recommend_id: @recommend.id)
	end

	def create
		@recommend = Recommend.new(recommend_params)
		@recommend.user_id = current_user.id
		@artist = Artist.find(params[:artist_id])
		@recommend.artist_id = @artist.id
		@url = params[:recommend][:url]
    	url = @url.last(11)
    	@recommend.url = url
		if @recommend.save
	       redirect_back(fallback_location: root_path)
	    else
	       flash[:recommend_error] = "全て入力してください。アーティスト、ミュージック20文字以内・説明150文字以内で入力をお願いします。"
	   	   redirect_back(fallback_location: root_path)
	   	end
	end

	def destroy
		@recommend = Recommend.find(params[:id])
		@recommend.destroy
		redirect_back(fallback_location: root_path)
	end

	private
	def recommend_params
		params.require(:recommend).permit(:artistname, :song, :url, :explanation)
	end
end

music-hub/app/helpers/recommends_helper.rb
module RecommendsHelper
  #urlテキストをハイパーリンクへ変換
  require "uri"

	def text_url_to_link text

	  URI.extract(text, ['http']).uniq.each do |url|
	    sub_text = ""
	    sub_text << "<a href=" << url << " target=\"_blank\">" << url << "</a>"

	    text.gsub!(url, sub_text)
	  end

	  return text
	end
end

music-hub/app/views/recommends/_commentarea.html.erb
<div class="col-xs-12">
    <div class="btn btn-default col-xs-2 comment-close-btn" id="close">閉じる</div>
    <%= form_for(comment, url: artist_recommend_comments_path(@artist.id, @recommend.id),method: :post) do |f| %>
    <%= f.text_area :comment, class: "comments-area" %>
    <%= f.submit ' コメント ',class: "btn btn-primary col-xs-12" %>
    <% end %>
</div>

music-hub/app/views/recommends/_myrecommend.html.erb
<% if Myrecommend.find_by(user_id: current_user.id, artist_id: artist.id, recommend_id: recommend.id ) %>
	<%= link_to "/artists/#{artist.id}/recommends/#{recommend.id}/myrecommends", method: :delete, remote: true do %>
		<i class="glyphicon glyphicon-star myrecommend-heart" aria-hidden="true"></i>
	<% end %>
<% else %>
	<%= link_to "/artists/#{artist.id}/recommends/#{recommend.id}/myrecommends", method: :post,remote: true do %>
		<i class="glyphicon glyphicon-star-empty myrecommend-heart" aria-hidden="true"></i>
	<% end %>
<% end %>

music-hub/app/views/recommends/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12" align="center">
            <h3><strong>みんなのおすすめ</strong></h>
        </div>
        <div class="col-xs-3">
            <h3 align="center">おすすめ作成</h3>
            <%= form_for(@recommend, url: artist_recommends_path(@artist),method: :post) do |f| %>
            <div class="col-xs-12">
                <h4>アーティスト</h4>
                <%= f.text_field :artistname, class: "form-control" %>
            </div>
            <div class="col-xs-12">
                <h4>ミュージック</h4>
                <%= f.text_field :song ,class: "form-control"%>
            </div>
            <div class="col-xs-12">
                <h4>YouTube URL</h4>
                <p>※https://www.youtube.com/watch?v=○○○○○○○○○○○にあたるURLを入力してください。</p>
                <%= f.url_field :url ,class: "form-control"%>
            </div>
            <div class="col-xs-12">
                <h4>説明</h4>
                <%= f.text_area :explanation ,class: "form-control"%>
            </div>
            <div class="col-xs-12 recommend-submit">
                <%= f.submit ' 投稿する ',class: 'btn btn-primary col-xs-12' %>
            </div>
            <% end %>
        </div>
        <div class="col-xs-9">
            <%= flash[:recommend_error] %>
            <div class="row">
                <div class="col-xs-12">
                    <% @recommends.each do |recommend| %>
                    <div class="form-group">
                        <table class="table">
                            <tr>
                                <th class="col-xs-2">
                                    <%= attachment_image_tag recommend.user,:image, size:"100x100", format: 'jpeg' , fallback: "no_image.jpg"%><br>
                                    <%= recommend.user.name %>
                                </th>
                                <td class="col-xs-6">
                                    <p class="glyphicon glyphicon-user recommend-artist-name">
                                        <%= recommend.artistname %>
                                    </p><br>
                                    <p class="glyphicon glyphicon-headphones recommend-song">
                                        <%= recommend.song %>
                                    </p>
                                </td>
                                <td id="myrecommends-<%= (@recommend.id) %>">
                                    <%= render partial: "myrecommend", locals: { recommend: recommend, artist: @artist} %>
                                </td>
                                <td class="col-xs-4">
                                    <p class="to-comment" align="right">
                                        <%= link_to "コメントページへ", artist_recommend_path(@artist,recommend.id)%>
                                    </p>
                                    <p align="center">
                                        <% if recommend.user_id == current_user.id %>
                                        <%= link_to "削除する",artist_recommend_path(@artist,recommend.id),method: :delete, class: "btn btn-danger"%>
                                        <% end %>
                                    </p>
                                </td>
                            </tr>
                        </table>
                    </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

music-hub/app/views/recommends/show.html.erb
<div class="container">
    <div class="row" align="center">
        <h3 class="recommend-song-title"><strong>おすすめミュージック</strong></h3>
    </div>
    <div class="row">
        <div class="col-xs-6">
            <div class="col-xs-12">
                <iframe width="100%" height="300px" src="https://www.youtube.com/embed/<%= @recommend.url%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
            <div class="col-xs-3 recommend-user">
                <%= link_to user_path(@recommend.user.id) do %>
                <%= attachment_image_tag @recommend.user, :image, size:"80x80", format: 'jpeg' , fallback: "no_image.jpg"%>
                <p class="recommend-user-name">
                    <%= @recommend.user.name %>
                </p>
                <% end %>
            </div>
            <div class="col-xs-9">
                <table>
                    <tr>
                        <td>
                            <p class="glyphicon glyphicon-user comment-recommend-artist-name">
                                <strong>
                                    <%= @recommend.artistname %></strong>
                            </p>
                            <p class="glyphicon glyphicon-headphones comment-recommend-song">
                                <strong>
                                    <%= @recommend.song %></strong>
                            </p>
                            <p>
                                <%= @recommend.explanation %>
                            </p>
                        </td>
                    </tr>
                </table>
                <div class="btn btn-primary col-xs-8" id="open">コメントする</div>
            </div>
        </div>
        <div class="col-xs-6">
            <div style="height:500px; width:100%; overflow:auto">
                <%= flash[:comment_error] %>
                <% @comments.each do |comment| %>
                <div class="row comment-box">
                    <div class="col-xs-2">
                        <%= link_to user_path(comment.user.id) do %>
                        <%= attachment_image_tag comment.user, :image, size:"60x60", format: 'jpeg' , fallback: "no_image.jpg"%>
                        <% end %>
                    </div>
                    <div class="col-xs-8">
                        <p>
                            <%= comment.user.name %>
                        </p>
                        <p>
                            <%= comment.comment %>
                        </p>
                    </div>
                    <div class="col-xs-1">
                        <% if comment.user_id == current_user.id %>
                        <%= link_to artist_recommend_comment_path(@artist.id,@recommend.id,comment.id), method: :delete do%>
                        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                        <% end %>
                        <% end %>
                    </div>
                </div>
                <% end %>
            </div>
        </div>
    </div>
</div>
<div class="recommend-fotter"></div>
<!--コメント入力モーダル表示用-->
<div id="modal">
    <%= render 'recommends/commentarea', comment: @comment %>
</div>
<script>
$('#open').click(function() {
    $('#modal').fadeIn();
});
$('#close').click(function() {
    $('#modal').fadeOut();
});
</script>