music-hub/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'homes#tops'
  get '/about' => 'homes#about'
  get 'events', to: 'events#events', as: 'user_calendar'
  get 'events_artist', to: 'events#event', as: 'artist_calendar'

  #artistお気に入り登録・解除
  post '/artists/:artist_id/favorites' => "favorites#create"
  delete '/artists/:artist_id/favorites' => "favorites#destroy"
  get '/users/:id/favorites' => "users#favorite",as: 'favorites'

  #recommendお気に入り登録・解除
  post '/artists/:artist_id/recommends/:recommend_id/myrecommends' => "myrecommends#create"
  delete '/artists/:artist_id/recommends/:recommend_id/myrecommends' => "myrecommends#destroy"
  get '/users/:id/myrecommends' => "users#myrecommend",as: 'myrecommends'

  #userのfullcalendaer表示用
  get '/users/:user_id/events' => "events#user_index",as: 'user_events'

  #userのフォロー、フォロワーのviewページ
  get 'users/:id/follows' => 'users#following',as: 'follows'
  get 'users/:id/followers' => 'users#followers',as: 'followers'

  resources :users, only: [:show, :edit, :update, :destroy]

  resources :artists, only: [:index, :new, :edit, :create, :update, :destroy] do
    get :search, on: :collection
    #eventsのindexをartistのfullcalendar表示用として使用
    resources :events, only: [:index, :destroy, :update]
    resources :recommends,only: [:index, :show, :create, :destroy] do
      resources :comments,only: [:create, :destroy]
    end
  end

  resources :events, only: [:create]
  resources :relationships, only: [:create, :destroy]
end

music-hub/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music-hub/app/models/artist.rb
class Artist < ApplicationRecord
	attachment :image

	belongs_to :user
	has_many :events
	has_many :favorites
	has_many :recommends, dependent: :destroy
	has_many :myrecommends, dependent: :destroy

	validates :name ,{presence: true, length: {maximum: 20}}
    validates :explanation ,{presence: true, length: {maximum: 150}}

    def self.artist_serach(search)
    	Artist.where(['name LIKE ?', "%#{search}%"])
	end
end

music-hub/app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :recommend

	validates :comment,{presence: true, length: {maximum: 150}}
end

music-hub/app/models/event.rb
class Event < ApplicationRecord

	belongs_to :user
	belongs_to :artist

	validates :title, {presence: true,length: {maximum: 20}}
	validates :start, presence: true
	validates :end, presence: true
	validates :share, presence: true
	validates :venue, {presence: true,length: {maximum: 30}}
	validates :url, {presence: true,format: /\A#{URI::regexp(%w(http https))}\z/}
	validates :memo, {presence: true, length: {maximum: 150}}

	#スケジュールをシェアするかしないか
	enum share: { シェアする:0, シェアしない:1 }
end

music-hub/app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :artist

	validates_uniqueness_of :artist_id, scope: :user_id
end

music-hub/app/models/myrecommend.rb
class Myrecommend < ApplicationRecord
	belongs_to :user
	belongs_to :recommend
	belongs_to :artist

	validates_uniqueness_of :recommend_id, scope: :user_id
end

music-hub/app/models/recommend.rb
class Recommend < ApplicationRecord
	belongs_to :user
	belongs_to :artist
	has_many :myrecommends, dependent: :destroy
	has_many :comments, dependent: :destroy

	validates :artistname, {presence: true,length: {maximum: 20}}
	validates :song, {presence: true,length: {maximum: 20}}
	validates :url, presence: true
	validates :explanation, {presence: true,length: {maximum: 150}}
end

music-hub/app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

music-hub/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, uniqueness: { case_sensitive: :false }, length: { maximum: 20 }, presence: true
  validates :introduction,length:{maximum:150}
  validates :email, presence: true

  attachment :image

  has_many :artists
  has_many :events, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :recommends, dependent: :destroy
  has_many :myrecommends, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  # ユーザーをフォローする
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  # ユーザーをアンフォローする
  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    self.followings.include?(other_user)
  end
end

music-hub/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def tops
  end

  def about
  end
end

music-hub/app/helpers/application_helper.rb
module ApplicationHelper
end

music-hub/app/helpers/artists_helper.rb
module ArtistsHelper
end

music-hub/app/helpers/comments_helper.rb
module CommentsHelper
end

music-hub/app/helpers/events_helper.rb
module EventsHelper
end

music-hub/app/helpers/favorites_helper.rb
module FavoritesHelper
end

music-hub/app/helpers/homes_helper.rb
module HomesHelper
end

music-hub/app/helpers/myrecommends_helper.rb
module MyrecommendsHelper
end

music-hub/app/helpers/recommends_helper.rb
module RecommendsHelper
  #urlテキストをハイパーリンクへ変換
  require "uri"

	def text_url_to_link text

	  URI.extract(text, ['http']).uniq.each do |url|
	    sub_text = ""
	    sub_text << "<a href=" << url << " target=\"_blank\">" << url << "</a>"

	    text.gsub!(url, sub_text)
	  end

	  return text
	end
end

music-hub/app/helpers/searchs_helper.rb
module SearchsHelper
end

music-hub/app/helpers/users_helper.rb
module UsersHelper
end

music-hub/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>music hub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body data-turbolinks="false" id="top-background">
    <header>
        <div class="container">
            <div class="row-header-text">
                <% if user_signed_in? %>
                <!--if文でログイン時とログアウト時の表示を変更-->
                <%= link_to image_tag('logo.png',  class: 'headerlogo'), root_path %>
                <div id="sp-menu">
                    <ul class="nav nav-pills navbar-right">
                        <li class="topmenu" href="#">
                            <%= link_to ' My Page ', user_path(current_user)%>
                        </li>
                        <li class="topmenu" href="#">
                            <%= link_to ' Artists ', artists_path%>
                        </li>
                        <li class="topmenu" href="#">
                            <%= link_to ' Search ', root_path%>
                        </li>
                        <li class="topmenu" href="#">
                            <%= link_to ' About ', about_path %>
                        <li class="topmenu" href="#">
                            <%= link_to ' Logout ', destroy_user_session_path, method: :delete, data: { confirm: 'ログアウトしますか？' }%>
                        </li>
                    </ul>
                </div>
                <div id="hm-icon">
                    <a class="menu-trigger" href="#">
                        <span></span>
                        <span></span>
                        <span></span>
                    </a>
                </div>
                <% else %>
                <%= link_to image_tag('logo.png', class: 'headerlogo'), root_path %>
                <div id="sp-menu">
                    <ul class="nav nav-pills">
                        <li class="topmenu" href="#">
                            <%= link_to ' Top ', root_path %>
                        </li>
                        <li class="topmenu" href="#">
                            <%= link_to ' About ', about_path %>
                        </li>
                        <li class="topmenu" href="#">
                            <%= link_to ' Sign Up ',new_user_registration_path %>
                        </li>
                        <li class="topmenu" href="#">
                            <%= link_to ' Log In ', new_user_session_path %>
                        </li>
                        <% end %>
                    </ul>
                </div>
                <div id="hm-icon">
                    <a class="menu-trigger" href="#">
                        <span></span>
                        <span></span>
                        <span></span>
                    </a>
                </div>
            </div>
        </div>
    </header>
    <%= yield %>
</body>

</html>